// sample-ui/src/app/documentation/bifrost/sample-code/ts/helloworld/helloworld.component.ts
import { Component, OnInit } from '@angular/core';
import { AbstractBase } from '@vmw/bifrost/core';

@Component({
    selector: 'ts-hello-world',
    template: `{{message}}`
})
export class HelloWorldComponent extends AbstractBase implements OnInit {

    public message: string;

    constructor() {
        super('HelloWorldComponent');
    }

    ngOnInit() {

        // define a channel to talk on.
        const someChannel = 'some-channel';

        // listen for requests on 'someChannel' and return a response.
        this.bus.respondOnce(someChannel)
            .generate(
                (request: string) => {
                    this.log.info(`Request Received: ${request}, Sending Response...`);
                    return 'world';
                }
            );

        this.log.info('Sending Request');

        // send request 'hello' on channel 'someChannel'.
        this.bus.requestOnce(someChannel, 'hello')
            .handle(
                (response: string) => {
                    this.message = `hello ${response}`;
                }
            );

    }
}

// sample-ui/src/app/documentation/bifrost/sample-code/react/HelloWorld.tsx
import React, { useState, useEffect } from 'react';
import { useBifrost } from '../../../../react-bifrost';

export default function HelloWorld(props: any) {
  const [message, setMessage] = useState('');
  const bifrost = useBifrost();

  // define a channel to talk on.
  const myChannel = 'some-channel';

  useEffect(() => {
    // listen for requests on 'myChannel' and return a response.
    bifrost.bus.respondOnce(myChannel).generate((request: string) => {
        bifrost.log.info(`Request Received: ${request}, Sending Response...`);
        return 'world';
    });

    bifrost.log.info('Sending Request');

    // send request 'hello' on channel 'myChannel'.
    bifrost.bus.requestOnce(myChannel, 'hello').handle((response: string) => {
        setMessage(`hello ${response}`);
    });
  }, []);

  return <div>{message}</div>;
}
